# .github/workflows/build.yml
name: Build Binaries

on:
  release:
    types: [created]
  workflow_dispatch:
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true   # ← opt into Node 24 now

permissions:
  contents: write
  
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      # --- Python +  CX_Freeze ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        env:
          VGAMEPAD_SKIP_VIGEMBUS_INSTALL: true
        shell: pwsh
        run: |
          pip install vgamepad@git+https://github.com/yannbouteiller/vgamepad.git
          pip install -r requirements.txt
          pip install cx_Freeze freeze-core nuitka pyinstaller

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          pip install -r requirements.txt
          pip install cx_Freeze freeze-core nuitka pyinstaller

      # --- Build ---
      - name: Build with CX_Freeze (Linux)
        if: runner.os == 'Linux'
        run: |
          python setup.py bdist_appimage
        
      - name: Build with CX_Freeze (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          python setup.py bdist_msi

     # --- Build Nuitka ---
      - name: Build with nuitka (linux)
        if: runner.os == 'Linux'
        run : |
          python -m nuitka --assume-yes-for-downloads --output-dir=dist --output-filename=OSCLeash-nuitka --mode=onefile --linux-icon=Resources/VRChatOSCLeash.png --no-prefer-source-code OSCLeash.py

      - name: Build with nuitka (windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          python -m nuitka --assume-yes-for-downloads --output-dir=dist --output-filename=OSCLeash-nuitka.exe --mode=onefile --windows-icon-from-ico=Resources\VRChatOSCLeash.ico --no-prefer-source-code OSCLeash.py

     # --- Build Nuitka ---
      - name: Build with pyinstaller (linux)
        if: runner.os == 'Linux'
        run : |
          pyinstaller --workpath=pyinstallbuild --distpath=dist -n OSCLeash-pyinstaller -F OSCLeash.py

      - name: Build with pyinstaller (windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          pyinstaller --workpath=pyinstallbuild --distpath=dist -i Resources\VRChatOSCLeash.ico -n OSCLeash-pyinstaller.exe -F OSCLeash.py

      # --- Upload ---
      - name: Upload binary
        uses: actions/upload-artifact@v6
        with:
          name: binaries-${{ matrix.os }}
          path: |
            dist/*.AppImage
            dist/*.msi
            dist/*.exe
            dist/OSCLeash-nuitka
            dist/OSCLeash-pyinstaller
          retention-days: 30

      - name: Upload to Release (CX_Freeze)
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.AppImage
            dist/*.msi
            dist/*.exe
            dist/OSCLeash-nuitka
            dist/OSCLeash-pyinstaller

